#!/bin/sh
SolutionDir="../../"

cflags() {
	solution=`${SolutionDir}get --cflags $1`
	project="-std=c++14 -fPIC -fvisibility=hidden"
	project="$project
	-Dimgui_EXPORTS
	-DIMGUI_USER_CONFIG=\"imgui_config.h\"
	-I.
	-Idear_bindings_generated
	-Idear_bindings_generated/backends
	-Iimgui
	-Iimgui/backends
	"
	libsdl3=`pkg-config --cflags sdl3`
	echo $solution $project $libsdl3
}
ldflags() {
	solution=`${SolutionDir}get --ldflags $1`
	project="-Wl,-Bsymbolic"
	echo $solution $project
}
sources() {
	# This script part is only tested on Debian 13, to be used only when going to make ABI-breaking upgrades
	set -xe
	rm -rf imgui
	git clone -q -c advice.detachedHead=false --depth 1 -b v1.92.5-docking https://github.com/ocornut/imgui.git
	( cd imgui && rm -rf .[a-z]* docs examples misc )
	find imgui/backends/ -type f \! -regex '.*sdl\(gpu\)?3.*' -print0 | xargs -r0 rm

	rm -rf dear_bindings
	git clone -q -c advice.detachedHead=false --depth 1 -b DearBindings_v0.17_ImGui_v1.92.5-docking https://github.com/dearimgui/dear_bindings.git
	( cd dear_bindings && rm -rf .[a-z]* docs examples )
	
	rm -rf dear_bindings_generated
	mkdir -p dear_bindings_generated/backends
	if [ ! -d dear_venv ]; then
		python3 -m venv dear_venv
		dear_venv/bin/pip install -r dear_bindings/requirements.txt
	fi
	(
		cd dear_bindings
		../dear_venv/bin/python dear_bindings.py -o ../dear_bindings_generated/dcimgui ../imgui/imgui.h
		../dear_venv/bin/python dear_bindings.py -o ../dear_bindings_generated/dcimgui_internal --include ../imgui/imgui.h ../imgui/imgui_internal.h
		../dear_venv/bin/python dear_bindings.py --backend --include ../imgui/imgui.h --imconfig-path ../imgui/imconfig.h -o ../dear_bindings_generated/backends/dcimgui_impl_sdl3 ../imgui/backends/imgui_impl_sdl3.h
		../dear_venv/bin/python dear_bindings.py --backend --include ../imgui/imgui.h --imconfig-path ../imgui/imconfig.h -o ../dear_bindings_generated/backends/dcimgui_impl_sdlgpu3 ../imgui/backends/imgui_impl_sdlgpu3.h
	)
	rm -rf dear_bindings dear_venv dear_bindings_generated/*.json

}
case $1 in
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	--sources) sources $2 ;;
	*) echo "Usage $0 (--cflags|--ldflags|--sources) (Release|Debug)" >&2 ;;
esac

