#!/bin/sh
#
# This file is part of LLSS.
#
# LLSS is free software: you can redistribute it and/or modify it under the terms of the
# Affero GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# LLSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with LLSS.
# If not, see <https://www.gnu.org/licenses/>. See LICENSE file at root of this git repo.
#
# Copyright 2025 ludolpif <ludolpif@gmail.com>
#
build_dep() {
	case "$1" in
		Debug|Release) _prebuilt_systemlibs; sources ;;
		SystemLibs) _build_systemlibs ;;
		*) _usage ;;
	esac
}
cflags() {
	case "$1" in
		Debug) solution="-ggdb3 -O0 -D_DEBUG" ;;
		Release) solution="-g -O2 -DNDEBUG" ;;
		*) _usage ;;
	esac
	echo $solution # -flto=auto (is very slow)
}
ldflags() {
	solution=""
	echo $solution
}
name() {
	echo "build-dep"
}
prettyos() {
	case $(uname -s) in
		Linux) os="$( . /etc/os-release && echo $ID-$VERSION_CODENAME )" ;;
		Darwin) os="MacOS" ;;
		*) echo "Unknown platform" >&2
	esac
	echo $os
}
sources() {
	set -xe
	for dir in ecs ui
	do
		( cd lib/$dir && ./get --sources )
	done
}
version() {
	grep "define LIB_VERSION_STR" include/metadata.h | cut -d'"' -f2
}
_build_systemlibs() {
	set -xe
	( cd lib/platform && ./get --sources )
	# SDL3 build-dep
	sudo apt-get install build-essential cmake debhelper fcitx-libs-dev glslang-tools libasound2-dev libdbus-1-dev libdecor-0-dev libdrm-dev libegl-dev libgbm-dev libgl-dev libgles-dev libibus-1.0-dev libpipewire-0.3-dev libpulse-dev libsndio-dev libudev-dev liburing-dev libvulkan-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev pkgconf wayland-protocols xxd graphviz doxygen
	# missing libusb2-dev libusbhid-dev but build don't fail
	( cd lib/platform/sdl3-deb/libsdl3-* && LANG=C dpkg-buildpackage -uc -us && rm -f libsdl3-doc* libsdl3-tests* )
}
_prebuilt_systemlibs() {
	set -xe
	zipname=build-dep-$(version)-$(prettyos)-SystemLibs.zip
        url=https://ludolpif.fr/pub/llss/artifacts/$zipname
        [ -f $zipname ] || curl -Lfo $zipname $url
        unzip -q $zipname
        rm -f $zipname
}

_usage() {
	echo "Usage $0 (--build-dep|--cflags|--ldflags|--name|--prettyos|--sources|--version) [Debug|Release|SystemLibs]" >&2
	exit 1
}
case "$1" in
	--build-dep) build_dep "$2" ;;
	--cflags) cflags "$2" ;;
	--ldflags) ldflags "$2" ;;
	--name) name ;;
	--prettyos) prettyos ;;
	--sources) sources ;;
	--version) version ;;
	*) _usage ;;
esac

