#!/bin/sh
build_dep() {
	# SDL3 build-dep
	sudo apt-get install build-essential cmake debhelper fcitx-libs-dev glslang-tools libasound2-dev libdbus-1-dev libdecor-0-dev libdrm-dev libegl-dev libgbm-dev libgl-dev libgles-dev libibus-1.0-dev libpipewire-0.3-dev libpulse-dev libsndio-dev libudev-dev liburing-dev libvulkan-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev pkgconf wayland-protocols xxd graphviz doxygen
	# missing libusb2-dev libusbhid-dev but build don't fail
	( cd lib/platform/sdl3-deb/libsdl3-* && LANG=C dpkg-buildpackage -uc -us )
}

cflags() {
	case "$1" in
		Debug)          solution="-ggdb3 -O0 -D_DEBUG" ;;
		Release)        solution="-g -O2 -DNDEBUG" ;;
		# removed RelWithDebInfo, we always can strip debug symbols after build
		*) echo "Bad BUILD_TYPE, should be Debug or Release" >&2; exit 1 ;;
	esac
	#case $(uname -s) in
	#	Linux)      lto="-flto=auto" ;;
	#	Darwin)     lto="-flto=auto" ;;
	#	Windows_NT) lto="" ;;
	#	*)          echo "Unknown platform" >&2
	#esac
	echo $solution # $lto (is very slow)
}
ldflags() {
	solution=""
	echo $solution
}
name() {
	echo "build-dep"
}
prettyos() {
	case $(uname -s) in
		Linux)      os="Linux" ;;
		Darwin)     os="MacOS" ;;
		Windows_NT) os="Windows" ;;
		*)          echo "Unknown platform" >&2
	esac
	echo $os
}
version() {
	echo "0.2.0.0"
}
case $1 in
	--build-dep) build_dep $2 ;;
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	--name) name $2 ;;
	--prettyos) prettyos $2 ;;
	--version) version $2 ;;
	*) echo "Usage $0 (--build-dep|--cflags|--ldflags|--prettyos|--name|--version) (Release|Debug)" >&2 ;;
esac

