#!/bin/sh
SolutionDir="../../"
SDL_VERSION=3.2.28

sources() {
	set -xe
	rm -rf sdl3-devel-vc
	url=https://github.com/libsdl-org/SDL/releases/download/release-${SDL_VERSION}/SDL3-devel-${SDL_VERSION}-VC.zip
	[ -f sdl3-devel-vc.zip ] || wget --show-progress -qO sdl3-devel-vc.zip $url
	unzip -q sdl3-devel-vc.zip
	mv SDL3-${SDL_VERSION} sdl3-devel-vc
	# rm -f sdl3-devel-vc.zip
}
case $1 in
	--sources) sources $2 ;;
	*) echo "Usage $0 (--sources) (Release|Debug)" >&2 ;;
esac

