#!/bin/sh
SolutionDir="../../"
version=3.2.10+ds

sources() {
	set -xe
	mkdir -p sdl3-deb
	cd sdl3-deb
	[ -f libsdl3-dev_$version-1_amd64.deb ] && exit 0

	pkg=libsdl3_$version
	for f in $pkg-1.dsc $pkg.orig.tar.xz $pkg-1.debian.tar.xz
	do
		[ -f $f ] || curl -o $f http://deb.debian.org/debian/pool/main/libs/libsdl3/$f
	done

	mkdir libsdl3-$version
	tar -xf $pkg.orig.tar.xz --strip-components=1 -C libsdl3-$version
	tar -xf $pkg-1.debian.tar.xz -C libsdl3-$version
	LANG=C dpkg-source --before-build libsdl3-$version
	rm -f $pkg.orig.tar.xz $pkg-1.debian.tar.xz
}
case $1 in
	--sources) sources $2 ;;
	*) echo "Usage $0 (--sources) (Debug|Release)" >&2 ;;
esac

