#!/bin/sh
#
# This file is part of LLSS.
#
# LLSS is free software: you can redistribute it and/or modify it under the terms of the
# Affero GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# LLSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with LLSS.
# If not, see <https://www.gnu.org/licenses/>. See LICENSE file at root of this git repo.
#
# Copyright 2025 ludolpif <ludolpif@gmail.com>
#
SolutionDir="../../"
version=3.2.10+ds

sources() {
	set -xe
	mkdir -p sdl3-deb
	cd sdl3-deb
	[ -f libsdl3-dev_$version-1_amd64.deb ] && exit 0

	pkg=libsdl3_$version
	for f in $pkg-1.dsc $pkg.orig.tar.xz $pkg-1.debian.tar.xz
	do
		[ -f $f ] || curl -o $f http://deb.debian.org/debian/pool/main/libs/libsdl3/$f
	done

	mkdir libsdl3-$version
	tar -xf $pkg.orig.tar.xz --strip-components=1 -C libsdl3-$version
	tar -xf $pkg-1.debian.tar.xz -C libsdl3-$version
	LANG=C dpkg-source --before-build libsdl3-$version
}
case $1 in
	--sources) sources $2 ;;
	*) echo "Usage $0 (--sources) (Debug|Release)" >&2 ;;
esac

