#
# Cross Platform Makefile
# For now, build for Windows and Mac uses VSCode MSBuild and XCode tools
#
.PHONY: all clean

# default value for command-line arguments (like make BUILD_TYPE=Release)
BUILD_TYPE ?= Debug

##---------------------------------------------------------------------
## BUILD RULES
##---------------------------------------------------------------------

all:
	
clean:
	
