#!/bin/sh
#
# This file is part of LLSS.
#
# LLSS is free software: you can redistribute it and/or modify it under the terms of the
# Affero GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# LLSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with LLSS.
# If not, see <https://www.gnu.org/licenses/>. See LICENSE file at root of this git repo.
#
# Copyright 2025 ludolpif <ludolpif@gmail.com>
#
SolutionDir="../../"

cflags() {
	solution=`${SolutionDir}get --cflags "$1"`
	project="-std=gnu99 -Iflecs -Dflecs_EXPORTS"
	echo $solution $project
}
sources() {
	set -xe
	rm -rf flecs
	mkdir flecs
	rawbase=https://github.com/SanderMertens/flecs/raw/refs/tags/v4.1.2
	curl -Lfo flecs/LICENSE $rawbase/LICENSE
	curl -Lfo flecs/flecs.h $rawbase/distr/flecs.h
	curl -Lfo flecs/flecs.c $rawbase/distr/flecs.c
	ls -l flecs
	patch -p1 < 0001-flecs-fix-msbuild-errors.patch
	sed --in-place -e 's|^#define flecs_STATIC|// \0|' flecs/flecs.h
}
_usage() {
	echo "Usage $0 (--cflags|--sources) [Debug|Release]" >&2
	exit 1
}
case "$1" in
	--cflags) cflags "$2" ;;
	--sources) sources ;;
	*) _usage ;;
esac

