#!/bin/sh
SolutionDir="../../"

cflags() {
	solution=`${SolutionDir}get --cflags $1`
	project="-std=gnu99 -Iflecs -Dflecs_EXPORTS"
	echo $solution $project
}
sources() {
	set -xe
	rm -rf flecs
	mkdir flecs
	rawbase=https://github.com/SanderMertens/flecs/raw/refs/tags/v4.1.2
	curl -Lfo flecs/LICENSE $rawbase/LICENSE
	curl -Lfo flecs/flecs.h $rawbase/distr/flecs.h
	curl -Lfo flecs/flecs.c $rawbase/distr/flecs.c
	ls -l flecs
	patch -p1 < 0001-flecs-fix-msbuild-errors.patch
	sed --in-place -e 's|^#define flecs_STATIC|// \0|' flecs/flecs.h
}
case $1 in
	--cflags) cflags $2 ;;
	--sources) sources $2 ;;
	*) echo "Usage $0 (--cflags|--sources) (Release|Debug)" >&2 ;;
esac

