#define BUILD_DEP_VERSION_MAJOR 0
#define BUILD_DEP_VERSION_MINOR 6
#define BUILD_DEP_VERSION_PATCH 1
#define BUILD_DEP_VERSION_BUILD 0
#define BUILD_DEP_VERSION_STR "0.6.1.0"
#define BUILD_DEP_RC_PRODUCTVER 0,6,1,0
#define BUILD_DEP_SDL_VERSION_STR "3.2.10"
