#define BUILD_DEP_VERSION_MAJOR 0
#define BUILD_DEP_VERSION_MINOR 5
#define BUILD_DEP_VERSION_PATCH 0
#define BUILD_DEP_VERSION_BUILD 0
#define BUILD_DEP_VERSION_STR "0.5.0.0"
#define BUILD_DEP_RC_PRODUCTVER 0,5,0,0
#define BUILD_DEP_SDL_VERSION_STR "3.2.10"
